### ISSUE TITLE
[BUG]网站访问不了

### ISSUE THREAD

**Issue by YIRU69** [nramos0/fluent-reader#30]
感谢作者
本来想尝试以下，但是[fluentreader.cc](https://fluentreader.cc/)访问不了
是本身的问题还是什么？

**Comment by nramos0** [comment]
目前在重新部署网站，我弄好了再在这里发信息。

**Comment by nramos0** [comment]
已恢复正常

**Comment by nramos0** [comment]
@YIRU69 如果使用的时候遇到什么问题可以发issue！

**Comment by YIRU69** [comment]
感谢
